import { expect, test } from '@playwright/test';
import { focusBoard } from './helpers/boardView';
import { powerView } from './helpers/powerView';
import { socketById } from '../src/engine/breadboard';

test('resistor placement, invalid spans, value editing, dragging, reversal and detachment', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const board = await focusBoard(page);
  await page.getByRole('button', { name: 'Place Resistor', exact: true }).click();
  await board.click('top-positive-1');
  await expect(page.locator('.placement-banner')).toBeVisible();
  await board.click('e60');
  await expect(page.locator('.connection-message')).toContainText('within the board');
  await board.hover('e10');
  await expect(page.locator('.socket-label')).toContainText('e10 ↔ e15');
  await board.click('e10');
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: e10 ↔ e15');
  await page.getByRole('combobox', { name: 'Resistance', exact: true }).selectOption('1000');
  const body = (a: string, b: string) => {
    const first = socketById(board.asset.sockets!, a)!, second = socketById(board.asset.sockets!, b)!;
    return board.project([(first.position[0] + second.position[0]) / 2, board.surface + 0.002, first.position[2]]);
  };
  let point = body('e10', 'e15'), target = board.socket('e20');
  await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(target.x, target.y, { steps: 10 }); await page.mouse.up();
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: e20 ↔ e25');
  await expect(page.getByRole('combobox', { name: 'Resistance', exact: true })).toHaveValue('1000');
  point = body('e20', 'e25'); target = board.socket('top-positive-10');
  await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(target.x, target.y, { steps: 10 }); await page.mouse.up();
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: e20 ↔ e25');
  await page.keyboard.press('r'); await page.keyboard.press('ArrowRight');
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: e26 ↔ e21');
  await page.screenshot({ path: 'artifacts/resistor-mounted.png' });
  await page.getByRole('button', { name: 'Detach resistor', exact: true }).click();
  await expect(page.locator('.mounted-info')).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Resistance', exact: true })).toHaveValue('1000');
  await page.keyboard.press('Delete');
  expect(errors).toEqual([]);
});

test('series LED current, voltage control, overload recovery and selected wire readings', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const scene = await powerView(page);
  await page.getByRole('button', { name: 'Place Resistor', exact: true }).click(); await scene.click('e10');
  await page.getByRole('button', { name: 'Place LED', exact: true }).click(); await scene.click('h20'); await page.keyboard.press('r');
  for (const [from, to] of [['positive', 'a10'], ['a15', 'j20'], ['j21', 'negative']]) { await scene.click(from); await scene.click(to); }
  await page.locator('.scene-item').filter({ hasText: 'Bench DC Power Supply' }).click();
  const voltage = page.getByRole('spinbutton', { name: 'Supply voltage in volts', exact: true });
  await expect(voltage).toHaveValue('5.0');
  await voltage.fill('13'); await voltage.press('Enter');
  await expect(voltage).toHaveValue('5.0');
  await expect(page.locator('.voltage-control')).toContainText('Previous value retained');
  await voltage.fill(''); await voltage.press('Enter'); await expect(voltage).toHaveValue('5.0');
  await page.getByRole('button', { name: 'Output on/off', exact: true }).click();
  await page.locator('.scene-item').filter({ hasText: 'Resistor' }).click();
  await expect(page.locator('.component-readings')).toContainText('9.09 mA');
  await expect(page.locator('.component-readings')).toContainText('0.027 W');
  await page.locator('.wire-item').first().click();
  await expect(page.locator('.wire-readings')).toContainText('5.00 V');
  await expect(page.locator('.wire-readings')).toContainText('9.09 mA');
  await expect(page.getByRole('button', { name: 'green wire', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: 'artifacts/wire-electrical-readings.png' });
  await page.locator('.wire-item').nth(1).click();
  await expect(page.locator('.wire-readings')).toContainText('2.00 V');
  await page.locator('.scene-item').filter({ hasText: 'Bench DC Power Supply' }).click();
  await page.getByRole('button', { name: 'Set supply to 12 volts', exact: true }).click();
  await page.locator('.scene-item').filter({ hasText: 'Resistor' }).click();
  await expect(page.locator('.component-readings')).toContainText('Resistor overload');
  await expect(page.locator('.component-readings')).toContainText('0.303 W');
  await page.locator('.scene-item').filter({ hasText: 'LED' }).last().click();
  await expect(page.locator('.led-power-state')).toHaveAttribute('data-state', 'overcurrent');
  await page.screenshot({ path: 'artifacts/resistor-led-overload.png' });
  await page.locator('.scene-item').filter({ hasText: 'Resistor' }).click();
  await page.getByRole('combobox', { name: 'Resistance', exact: true }).selectOption('1000');
  await expect(page.locator('.component-readings')).toContainText('10.00 mA');
  await expect(page.locator('.component-readings')).toContainText('0.100 W');
  await expect(page.locator('.component-warning')).toHaveCount(0);
  await page.locator('.scene-item').filter({ hasText: 'LED' }).last().click();
  await expect(page.locator('.led-power-state')).toHaveAttribute('data-state', 'on');
  await page.locator('.wire-item').last().click(); await page.getByRole('button', { name: 'Delete wire', exact: true }).click();
  await page.locator('.scene-item').filter({ hasText: 'LED' }).last().click();
  await expect(page.locator('.led-power-state')).toHaveAttribute('data-state', 'unconnected');
  expect(errors).toEqual([]);
});

test('narrow supply controls, reduced motion and independent voltage settings', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/'); await expect(page.locator('.model-thumbnail img')).toHaveCount(6);
  await page.locator('.model-card').filter({ hasText: 'Bench DC Power Supply' }).getByRole('button', { name: 'Add at view center', exact: true }).click();
  await page.getByRole('button', { name: 'Set supply to 3.3 volts', exact: true }).click();
  await page.locator('.scene-item').filter({ hasText: 'Bench DC Power Supply' }).first().click();
  await expect(page.getByRole('spinbutton', { name: 'Supply voltage in volts', exact: true })).toHaveValue('5.0');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Focus selected component' }).click();
  await expect(page.getByRole('button', { name: 'Set supply to 9 volts', exact: true })).toBeInViewport();
  await page.getByRole('button', { name: 'Set supply to 9 volts', exact: true }).click();
  await page.getByRole('button', { name: 'Output on/off', exact: true }).click();
  await page.screenshot({ path: 'artifacts/voltage-controls-narrow.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
