import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { Box3, PerspectiveCamera, Vector3 } from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { prepareModel } from '../src/lib/modelAssets';
import { createDemo, snapPosition } from '../src/lib/placement';
import { localToWorld, socketById } from '../src/engine/breadboard';
import type { Point3 } from '../src/types/workspace';

async function focusBoard(page: Page) {
  await page.goto('/');
  await expect(page.locator('.model-thumbnail img')).toHaveCount(3);
  if (!(await page.getByRole('complementary').isVisible())) await page.getByRole('button', { name: 'Toggle component library' }).click();
  await page.locator('.scene-item').filter({ hasText: 'Breadboard' }).click();
  const close = page.getByRole('complementary').getByRole('button', { name: 'Close component library' });
  if (await close.isVisible()) await close.click();
  await page.getByRole('button', { name: 'Top', exact: true }).click();
  await page.getByRole('button', { name: 'Focus selected component' }).click();
  const bytes = await readFile(new URL('../../models/breadboard.glb', import.meta.url));
  const gltf = await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), '');
  const asset = prepareModel(gltf.scene, { id: 'breadboard', label: '', description: '', url: '', scale: 0.1, rotation: [0, 0, 0] });
  const board = createDemo(Math.max(asset.size.x, asset.size.z))[0];
  const canvas = (await page.locator('canvas').boundingBox())!;
  const bounds = new Box3().setFromObject(asset.object).translate(new Vector3(board.position[0], 0, board.position[1])).expandByScalar(0.0005);
  const camera = new PerspectiveCamera(38, canvas.width / canvas.height, 0.00001, 100);
  const center = bounds.getCenter(new Vector3());
  const fov = 38 * Math.PI / 180;
  const distance = bounds.getSize(new Vector3()).length() / 2 / Math.sin(Math.min(fov, 2 * Math.atan(Math.tan(fov / 2) * camera.aspect)) / 2) * 1.18;
  camera.position.copy(center).addScaledVector(new Vector3(0, 1, 0.0001).normalize(), distance); camera.lookAt(center); camera.updateMatrixWorld(true);
  const project = (point: Point3) => { const p = new Vector3(...localToWorld(board, point)).project(camera); return { x: canvas.x + (p.x + 1) / 2 * canvas.width, y: canvas.y + (1 - p.y) / 2 * canvas.height }; };
  const socket = (id: string) => project(socketById(asset.sockets!, id)!.position);
  const click = async (id: string) => { const p = socket(id); await page.mouse.click(p.x, p.y); };
  const hover = async (id: string) => { const p = socket(id); await page.mouse.move(p.x, p.y); };
  return { project, socket, click, hover, surface: asset.sockets![0].position[1], asset, board, canvas };
}

test('draw, edit, recolor and delete wires; stationary right-click differs from pan', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const board = await focusBoard(page);
  await board.hover('e10');
  await expect(page.locator('.socket-label')).toContainText('e10');
  await board.click('e10');
  await expect(page.getByRole('region', { name: 'Wire properties' })).toContainText('Drawing wire');
  const bend = board.project([-0.01, board.surface + 0.005, 0.001]);
  await page.mouse.move(bend.x, bend.y);
  await page.mouse.click(bend.x, bend.y, { button: 'right' });
  await expect(page.locator('.wiring-panel')).toContainText('1 bends');
  await page.getByRole('button', { name: 'Add bend', exact: false }).click(); // same point is not duplicated
  await expect(page.locator('.wiring-panel')).toContainText('1 bends');
  await page.keyboard.press('Backspace');
  await expect(page.locator('.wiring-panel')).toContainText('0 bends');
  await page.mouse.move(bend.x + 20, bend.y);
  await page.keyboard.press('Enter');
  await expect(page.locator('.wiring-panel')).toContainText('1 bends');
  await board.click('e10');
  await expect(page.locator('.connection-message')).toContainText('different, unoccupied');
  await board.click('f20');
  await expect(page.locator('.wire-item')).toHaveCount(1);
  await expect(page.locator('.wiring-panel')).toContainText('e10 → f20');
  await page.getByRole('button', { name: 'red wire', exact: true }).click();
  await expect(page.getByRole('button', { name: 'red wire', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Bend 1', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Wire height in millimeters' }).fill('12');
  await expect(page.getByRole('spinbutton')).toHaveValue('12');
  await page.screenshot({ path: 'artifacts/wiring-desktop.png' });
  await page.getByRole('button', { name: 'Remove bend', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Bend 1', exact: true })).toHaveCount(0);
  // Add a new control point through the route's segment context menu.
  const start = board.socket('e10'), end = board.socket('f20');
  await page.mouse.click((start.x + end.x) / 2, (start.y + end.y) / 2, { button: 'right' });
  await expect(page.getByRole('menuitem', { name: 'Add bend here' })).toBeVisible();
  await page.getByRole('menuitem', { name: 'Add bend here' }).click();
  await expect(page.getByRole('button', { name: 'Bend 1', exact: true })).toBeVisible();
  const middle = { x: (start.x + end.x) / 2, y: (start.y + end.y) / 2 };
  await page.mouse.move(middle.x, middle.y); await page.mouse.down(); await page.mouse.move(middle.x + 30, middle.y - 25, { steps: 6 }); await page.mouse.up();
  await expect(page.locator('.wiring-heading')).toContainText('Bend 1');
  await page.locator('.wire-item').click();
  await page.getByRole('button', { name: 'Delete wire', exact: true }).click();
  await expect(page.locator('.wire-item')).toHaveCount(0);
  await board.click('e10');
  await expect(page.locator('.wiring-panel')).toContainText('Drawing wire');
  await expect(page.getByRole('button', { name: 'red wire', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.mouse.move(bend.x, bend.y); await page.mouse.down({ button: 'right' });
  await page.mouse.move(bend.x + 50, bend.y + 30, { steps: 8 }); await page.mouse.up({ button: 'right' });
  await expect(page.locator('.wiring-panel')).toContainText('0 bends');
  await page.keyboard.press('Escape');
  await expect(page.locator('.wiring-panel')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('LED insertion, occupied sockets, polarity flip, relocation, detachment and board cleanup', async ({ page }) => {
  const board = await focusBoard(page);
  await page.getByRole('button', { name: 'Place LED', exact: true }).click();
  await board.hover('top-positive-10');
  await board.click('top-positive-10');
  await expect(page.locator('.placement-banner')).toBeVisible();
  await expect(page.locator('.connection-message')).toContainText('not rails');
  await board.click('e30');
  await expect(page.locator('.connection-message')).toContainText('past column 30');
  await board.hover('e10');
  await expect(page.locator('.socket-label')).toContainText('+ e11');
  await board.click('e10');
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: + e11 / − e10');
  await page.keyboard.press('r');
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: + e10 / − e11');
  await page.keyboard.press('ArrowRight');
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: + e11 / − e12');
  await page.getByRole('button', { name: 'Place LED', exact: true }).click();
  await board.click('e11');
  await expect(page.locator('.connection-message')).toContainText('occupied');
  await page.keyboard.press('Escape');
  // Drag the mounted LED to another pair, then reject a rail drop.
  const from = board.socket('e11'), to = board.socket('e20');
  await page.mouse.move(from.x + 5, from.y); await page.mouse.down(); await page.mouse.move(to.x, to.y, { steps: 8 }); await page.mouse.up();
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: + e20 / − e21');
  const rail = board.socket('top-positive-20');
  await page.mouse.move(to.x + 5, to.y); await page.mouse.down(); await page.mouse.move(rail.x, rail.y, { steps: 8 }); await page.mouse.up();
  await expect(page.locator('.mounted-info')).toHaveText('Inserted: + e20 / − e21');
  await page.getByRole('button', { name: 'Front', exact: true }).click();
  await page.getByRole('button', { name: 'Focus selected component' }).click();
  await page.screenshot({ path: 'artifacts/mounted-led.png' });
  await page.getByRole('button', { name: 'Detach LED', exact: true }).click();
  await expect(page.locator('.mounted-info')).toHaveCount(0);
  await page.getByRole('button', { name: 'Focus selected component' }).click();
  await page.screenshot({ path: 'artifacts/detached-led.png' });
});

test('wire editing remains usable on a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const board = await focusBoard(page);
  await board.click('e5');
  await board.hover('f20');
  await page.screenshot({ path: 'artifacts/wiring-narrow-draft.png' });
  await board.click('f20');
  await expect(page.locator('.wiring-panel')).toContainText('e5 → f20');
  await page.getByRole('button', { name: 'blue wire', exact: true }).click();
  await page.screenshot({ path: 'artifacts/wiring-narrow.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Focus wire', exact: true }).click();
  await page.getByRole('button', { name: 'Delete wire', exact: true }).click();
  await expect(page.locator('.wiring-panel')).toHaveCount(0);
});

test('cross-board route and mounted LED follow board edits and clean up on deletion', async ({ page }) => {
  const setup = await focusBoard(page);
  for (const label of ['Bench DC Power Supply', 'LED']) {
    await page.locator('.scene-item').filter({ hasText: label }).click(); await page.keyboard.press('Delete');
  }
  await page.locator('.model-card').filter({ hasText: 'Breadboard' }).getByRole('button', { name: 'Add at view center' }).click();
  for (let i = 0; i < 14; i++) await page.keyboard.press('ArrowRight');
  const spacing = setup.asset.size.x / 10;
  const second = { ...setup.board, id: 'second', position: snapPosition(setup.board.position, spacing, true) };
  second.position[0] += 14 * spacing;
  const bounds = new Box3();
  for (const instance of [setup.board, second]) bounds.union(new Box3().setFromObject(setup.asset.object).translate(new Vector3(instance.position[0], 0, instance.position[1])));
  bounds.expandByScalar(0.0005);
  const camera = new PerspectiveCamera(38, setup.canvas.width / setup.canvas.height, 0.00001, 100);
  const center = bounds.getCenter(new Vector3()), fov = 38 * Math.PI / 180;
  const distance = bounds.getSize(new Vector3()).length() / 2 / Math.sin(Math.min(fov, 2 * Math.atan(Math.tan(fov / 2) * camera.aspect)) / 2) * 1.18;
  camera.position.copy(center).addScaledVector(new Vector3(0, 1, 0.0001).normalize(), distance); camera.lookAt(center); camera.updateMatrixWorld(true);
  const project = (point: Point3) => { const p = new Vector3(...point).project(camera); return { x: setup.canvas.x + (p.x + 1) / 2 * setup.canvas.width, y: setup.canvas.y + (1 - p.y) / 2 * setup.canvas.height }; };
  const socket = (instance: typeof second, id: string) => project(localToWorld(instance, socketById(setup.asset.sockets!, id)!.position));
  await page.getByRole('button', { name: 'Fit all components' }).click();
  const from = socket(setup.board, 'a1'), to = socket(second, 'a1');
  await page.mouse.click(from.x, from.y);
  const bend = project([0.09, setup.surface + 0.005, 0.055]);
  await page.mouse.move(bend.x, bend.y); await page.keyboard.press('Enter');
  await page.mouse.click(to.x, to.y);
  await expect(page.locator('.wire-item')).toHaveCount(1);
  await page.getByRole('button', { name: 'Place LED', exact: true }).click();
  const led = socket(setup.board, 'e10'); await page.mouse.click(led.x, led.y);
  await expect(page.locator('.mounted-info')).toContainText('+ e11');
  await page.locator('.scene-item').first().click(); await page.keyboard.press('r'); await page.keyboard.press('ArrowDown');
  const moved = { ...setup.board, rotation: Math.PI / 2, position: snapPosition([setup.board.position[0], setup.board.position[1] + spacing], spacing, true) };
  const movedEndpoint = socket(moved, 'a1'); await page.mouse.move(movedEndpoint.x, movedEndpoint.y);
  await expect(page.locator('.socket-label')).toContainText('a1 · occupied');
  await page.mouse.click(movedEndpoint.x, movedEndpoint.y);
  await expect(page.locator('.connection-message')).toContainText('occupied');
  await page.getByRole('button', { name: 'Fit all components' }).click();
  await page.screenshot({ path: 'artifacts/cross-board-wiring.png' });
  await page.locator('.scene-item').first().click(); await page.keyboard.press('Delete');
  await expect(page.locator('.wire-item')).toHaveCount(0);
  await page.locator('.scene-item').filter({ hasText: 'LED' }).click();
  await expect(page.locator('.mounted-info')).toHaveCount(0);
  await expect(page.locator('.scene-item')).toHaveCount(2);
});
